[workspace]

[package]
name = "pocket-pi-p4"
version = "0.1.0"
edition = "2021"
resolver = "2"
rust-version = "1.82"
publish = false

[[bin]]
name = "pocket-pi-p4"
harness = false

[profile.release]
opt-level = "s"
lto = "thin"
codegen-units = 1

[profile.dev]
debug = true
opt-level = "z"

[dependencies]
anyhow = "1"
log = "0.4"
serde_json = "1"
pocket-pi-agentos = { path = "../../crates/pocket-pi-agentos" }
pocket-pi-embedded = { path = "../../crates/pocket-pi-embedded" }
pocket-pi-protocols = { path = "../../crates/pocket-pi-protocols" }
pocket-pi-tools = { path = "../../crates/pocket-pi-tools" }
esp-idf-svc = { version = "0.52.1", features = ["critical-section"] }
embedded-svc = "0.29"
pocketjs-esp32p4-ppa = { git = "https://github.com/pocket-stack/pocketjs.git", rev = "9c809bbd047ddc75c27caa4990951a78d942477a", features = ["esp-idf"] }

[build-dependencies]
embuild = "0.33"

[[package.metadata.esp-idf-sys.extra_components]]
component_dirs = ["components/esp32_p4_wifi6_touch_lcd_5"]
bindings_header = "src/waveshare_bindings.h"

[[package.metadata.esp-idf-sys.extra_components]]
component_dirs = ["components/pocketjs_ppa"]

[[package.metadata.esp-idf-sys.extra_components]]
remote_component = { name = "espressif/esp_wifi_remote", version = "0.14.*" }

[[package.metadata.esp-idf-sys.extra_components]]
remote_component = { name = "espressif/esp_hosted", version = "1.4.*" }

[[package.metadata.esp-idf-sys.extra_components]]
remote_component = { name = "joltwallet/littlefs", version = "1.14.*" }
